services:
  sca-client:
    image: ghcr.io/fontys-pingmasters/sca-client:testing
    ports:
      - "81:80"
    networks:
      - sca_network

networks:
  sca_network:
    driver: bridge
    attachable: true
